export const routes = {
  home: '/',
  inbox: '/inbox',
  outbox: '/outbox',
  notifications: '/notifications',
  search: '/search',
  newRequest: '/requests/new',
  request: (id: string) => `/requests/${id}`,
  admin: {
    root: '/admin',
    routeTemplates: '/admin/route-templates',
    requestTypes: '/admin/request-types',
    users: '/admin/users',
    orgUnits: '/admin/org-units',
    audit: '/admin/audit',
    settings: '/admin/settings',
  },
  login: '/login',
  welcome: '/welcome',
} as const;
